#FROM cameronkerrnz/json-to-mmdb:latest
FROM json-to-mmdb:latest
# You might wonder why I didn't use the Dockerfile from the root of this
# repo. Its only because that file is one of the prime outputs, whereas
# .devcontainer is just about development time.
#
# We only need devcontainer for this to make it easier to hack on the
# code for the conversion app.
